@startuml
left to right direction

usecase "Evaluar Solicitud de Crédito" as usc1
:Agente: --> usc1

usecase "Enviar solicitud de crédito personal" as usc2
usecase "Enviar solicitud de crédito empresarial" as usc3

usc2 --|> usc1
usc3 --|> usc1
@enduml